version: "3"

vars:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-D warnings"

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  build:
    desc: Build the project
    cmds:
      - cargo build
    sources:
      - src/**/*.rs
      - Cargo.toml
    generates:
      - target/debug/tbd-cfg

  test:
    desc: Run all tests
    cmds:
      - cargo test --all-features

  integration-test:
    desc: Run integration tests (requires ansible)
    deps: [check-ansible]
    cmds:
      - cargo test --test '*' --features integration

  check-ansible:
    desc: Check if ansible is installed
    cmds:
      - ansible --version
    silent: true

  check:
    desc: Run all checks (format, clippy, test)
    cmds:
      - task: fmt-check
      - task: clippy
      - task: test

  clippy:
    desc: Run clippy
    cmds:
      - cargo clippy --all-targets --all-features -- -D warnings

  fmt:
    desc: Format code
    cmds:
      - cargo fmt --all

  fmt-check:
    desc: Check code formatting
    cmds:
      - cargo fmt --all -- --check

  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean

  install-tools:
    desc: Install development tools
    cmds:
      - cargo install cargo-watch cargo-audit cargo-outdated
      - rustup component add clippy rustfmt

  audit:
    desc: Run security audit
    cmds:
      - cargo audit

  outdated:
    desc: Check for outdated dependencies
    cmds:
      - cargo outdated

  ci:
    desc: Run CI pipeline locally
    cmds:
      - task: clean
      - task: check
      - task: build
      - task: test

  run:
    desc: Run the CLI with arguments
    cmds:
      - cargo run -- {{.CLI_ARGS}}

  dev:
    desc: Start development environment with file watching
    cmds:
      - cargo watch -x 'run -- {{.CLI_ARGS}}'

  # Example configuration tasks
  example:
    desc: Create example configuration
    dir: target
    cmds:
      - mkdir -p examples/ansible
      - cp ../examples/playbook.yml examples/ansible/
      - cp ../examples/inventory.yml examples/ansible/

  apply-example:
    desc: Apply example configuration
    deps: [example]
    dir: target/examples
    cmds:
      - cargo run -- apply -c ansible/playbook.yml -i ansible/inventory.yml
